'''File containing all instructions for the M6800 assembly language.'''

from enum import IntEnum


class AddressMode(IntEnum):
    '''All of the various addressing modes for the M6800'''
    ACCUMULATOR = 1
    IMMEDIATE = 2
    DIRECT = 3
    EXTENDED = 4
    INDEXED = 5
    IMPLIED = 6
    RELATIVE = 7


BRANCH_INSTRUCTIONS = [
    0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f
]

JMP_INSTRUCTIONS = [
    0x20, 0x6E, 0x7E  # 0x20 is unconditional branch, the other two are unconditional jumps
]

CALL_INSTRUCTIONS = [0x8D, 0xAD, 0xBD]

RETURN_INSTRUCTIONS = [0x39]

INSTRUCTIONS = {
    # Opcode: (mnemonic, length, accumulator, address mode)
    0x01: ('NOP', 1, None, AddressMode.IMPLIED),
    0x06: ('TAP', 1, None, AddressMode.IMPLIED),
    0x07: ('TPA', 1, None, AddressMode.IMPLIED),
    0x08: ('INX', 1, None, AddressMode.IMPLIED),
    0x09: ('DEX', 1, None, AddressMode.IMPLIED),
    0x0A: ('CLV', 1, None, AddressMode.IMPLIED),
    0x0B: ('SEV', 1, None, AddressMode.IMPLIED),
    0x0C: ('CLC', 1, None, AddressMode.IMPLIED),
    0x0D: ('SEC', 1, None, AddressMode.IMPLIED),
    0x0E: ('CLI', 1, None, AddressMode.IMPLIED),
    0x0F: ('SEI', 1, None, AddressMode.IMPLIED),
    0x10: ('SBA', 1, None, AddressMode.IMPLIED),
    0x11: ('CBA', 1, None, AddressMode.IMPLIED),
    0x16: ('TAB', 1, None, AddressMode.IMPLIED),
    0x17: ('TBA', 1, None, AddressMode.IMPLIED),
    0x19: ('DAA', 1, None, AddressMode.IMPLIED),
    0x1B: ('ABA', 1, None, AddressMode.IMPLIED),
    0x20: ('BRA', 2, None, AddressMode.RELATIVE),
    0x22: ('BHI', 2, None, AddressMode.RELATIVE),
    0x23: ('BLS', 2, None, AddressMode.RELATIVE),
    0x24: ('BCC', 2, None, AddressMode.RELATIVE),
    0x25: ('BCS', 2, None, AddressMode.RELATIVE),
    0x26: ('BNE', 2, None, AddressMode.RELATIVE),
    0x27: ('BEQ', 2, None, AddressMode.RELATIVE),
    0x28: ('BVC', 2, None, AddressMode.RELATIVE),
    0x29: ('BVS', 2, None, AddressMode.RELATIVE),
    0x2A: ('BPL', 2, None, AddressMode.RELATIVE),
    0x2B: ('BMI', 2, None, AddressMode.RELATIVE),
    0x2C: ('BGE', 2, None, AddressMode.RELATIVE),
    0x2D: ('BLT', 2, None, AddressMode.RELATIVE),
    0x2E: ('BGT', 2, None, AddressMode.RELATIVE),
    0x2F: ('BLE', 2, None, AddressMode.RELATIVE),
    0x30: ('TSX', 1, None, AddressMode.IMPLIED),
    0x31: ('INS', 1, None, AddressMode.IMPLIED),
    0x32: ('PUL', 1, 'ACCA', AddressMode.ACCUMULATOR),
    0x33: ('PUL', 1, 'ACCB', AddressMode.ACCUMULATOR),
    0x34: ('DES', 1, None, AddressMode.IMPLIED),
    0x35: ('TXS', 1, None, AddressMode.IMPLIED),
    0x36: ('PSH', 1, 'ACCA', AddressMode.ACCUMULATOR),
    0x37: ('PSH', 1, 'ACCB', AddressMode.ACCUMULATOR),
    0x39: ('RTS', 1, None, AddressMode.IMPLIED),
    0x3B: ('RTI', 1, None, AddressMode.IMPLIED),
    0x3E: ('WAI', 1, None, AddressMode.IMPLIED),
    0x3F: ('SWI', 1, None, AddressMode.IMPLIED),
    0x40: ('NEG', 1, 'ACCA', AddressMode.ACCUMULATOR),
    0x43: ('COM', 1, 'ACCA', AddressMode.ACCUMULATOR),
    0x44: ('LSR', 1, 'ACCA', AddressMode.ACCUMULATOR),
    0x46: ('ROR', 1, 'ACCA', AddressMode.ACCUMULATOR),
    0x47: ('ASR', 1, 'ACCA', AddressMode.ACCUMULATOR),
    0x48: ('ASL', 1, 'ACCA', AddressMode.ACCUMULATOR),
    0x49: ('ROL', 1, 'ACCA', AddressMode.ACCUMULATOR),
    0x4A: ('DEC', 1, 'ACCA', AddressMode.ACCUMULATOR),
    0x4C: ('INC', 1, 'ACCA', AddressMode.ACCUMULATOR),
    0x4D: ('TST', 1, 'ACCA', AddressMode.ACCUMULATOR),
    0x4F: ('CLR', 1, 'ACCA', AddressMode.ACCUMULATOR),
    0x50: ('NEG', 1, 'ACCB', AddressMode.ACCUMULATOR),
    0x53: ('COM', 1, 'ACCB', AddressMode.ACCUMULATOR),
    0x54: ('LSR', 1, 'ACCB', AddressMode.ACCUMULATOR),
    0x56: ('ROR', 1, 'ACCB', AddressMode.ACCUMULATOR),
    0x57: ('ASR', 1, 'ACCB', AddressMode.ACCUMULATOR),
    0x58: ('ASL', 1, 'ACCB', AddressMode.ACCUMULATOR),
    0x59: ('ROL', 1, 'ACCB', AddressMode.ACCUMULATOR),
    0x5A: ('DEC', 1, 'ACCB', AddressMode.ACCUMULATOR),
    0x5C: ('INC', 1, 'ACCB', AddressMode.ACCUMULATOR),
    0x5D: ('TST', 1, 'ACCB', AddressMode.ACCUMULATOR),
    0x5F: ('CLR', 1, 'ACCB', AddressMode.ACCUMULATOR),
    0x60: ('NEG', 2, None, AddressMode.INDEXED),
    0x63: ('COM', 2, None, AddressMode.INDEXED),
    0x64: ('LSR', 2, None, AddressMode.INDEXED),
    0x66: ('ROR', 2, None, AddressMode.INDEXED),
    0x67: ('ASR', 2, None, AddressMode.INDEXED),
    0x68: ('ASL', 2, None, AddressMode.INDEXED),
    0x69: ('ROL', 2, None, AddressMode.INDEXED),
    0x6A: ('DEC', 2, None, AddressMode.INDEXED),
    0x6C: ('INC', 2, None, AddressMode.INDEXED),
    0x6D: ('TST', 2, None, AddressMode.INDEXED),
    0x6E: ('JMP', 2, None, AddressMode.INDEXED),
    0x6F: ('CLR', 2, None, AddressMode.INDEXED),
    0x70: ('NEG', 3, None, AddressMode.EXTENDED),
    0x73: ('COM', 3, None, AddressMode.EXTENDED),
    0x74: ('LSR', 3, None, AddressMode.EXTENDED),
    0x76: ('ROR', 3, None, AddressMode.EXTENDED),
    0x77: ('ASR', 3, None, AddressMode.EXTENDED),
    0x78: ('ASL', 3, None, AddressMode.EXTENDED),
    0x79: ('ROL', 3, None, AddressMode.EXTENDED),
    0x7A: ('DEC', 3, None, AddressMode.EXTENDED),
    0x7C: ('INC', 3, None, AddressMode.EXTENDED),
    0x7D: ('TST', 3, None, AddressMode.EXTENDED),
    0x7E: ('JMP', 3, None, AddressMode.EXTENDED),
    0x7F: ('CLR', 3, None, AddressMode.EXTENDED),
    0x80: ('SUB', 2, 'ACCA', AddressMode.IMMEDIATE),
    0x81: ('CMP', 2, 'ACCA', AddressMode.IMMEDIATE),
    0x82: ('SBC', 2, 'ACCA', AddressMode.IMMEDIATE),
    0x84: ('AND', 2, 'ACCA', AddressMode.IMMEDIATE),
    0x85: ('BIT', 2, 'ACCA', AddressMode.IMMEDIATE),
    0x86: ('LDA', 2, 'ACCA', AddressMode.IMMEDIATE),
    0x88: ('EOR', 2, 'ACCA', AddressMode.IMMEDIATE),
    0x89: ('ADC', 2, 'ACCA', AddressMode.IMMEDIATE),
    0x8A: ('ORA', 2, 'ACCA', AddressMode.IMMEDIATE),
    0x8B: ('ADD', 2, 'ACCA', AddressMode.IMMEDIATE),
    0x8C: ('CPX', 3, 'ACCA', AddressMode.IMMEDIATE),
    0x8D: ('BSR', 2, None, AddressMode.RELATIVE),
    0x8E: ('LOS', 2, None, AddressMode.IMMEDIATE),
    0x90: ('SUB', 2, 'ACCA', AddressMode.DIRECT),
    0x91: ('CMP', 2, 'ACCA', AddressMode.DIRECT),
    0x92: ('SBC', 2, 'ACCA', AddressMode.DIRECT),
    0x94: ('AND', 2, 'ACCA', AddressMode.DIRECT),
    0x95: ('BIT', 2, 'ACCA', AddressMode.DIRECT),
    0x96: ('LDA', 2, 'ACCA', AddressMode.DIRECT),
    0x97: ('STA', 2, 'ACCA', AddressMode.DIRECT),
    0x98: ('EOR', 2, 'ACCA', AddressMode.DIRECT),
    0x99: ('ADC', 2, 'ACCA', AddressMode.DIRECT),
    0x9A: ('ORA', 2, 'ACCA', AddressMode.DIRECT),
    0x9B: ('ADD', 2, 'ACCA', AddressMode.DIRECT),
    0x9C: ('CPX', 2, None, AddressMode.DIRECT),
    0x9E: ('LOS', 2, None, AddressMode.DIRECT),
    0x9F: ('STS', 2, None, AddressMode.DIRECT),
    0xA0: ('SUB', 2, 'ACCA', AddressMode.INDEXED),
    0xA1: ('CMP', 2, 'ACCA', AddressMode.INDEXED),
    0xA2: ('SBC', 2, 'ACCA', AddressMode.INDEXED),
    0xA4: ('AND', 2, 'ACCA', AddressMode.INDEXED),
    0xA5: ('BIT', 2, 'ACCA', AddressMode.INDEXED),
    0xA6: ('LDA', 2, 'ACCA', AddressMode.INDEXED),
    0xA7: ('STA', 2, 'ACCA', AddressMode.INDEXED),
    0xA8: ('EOR', 2, 'ACCA', AddressMode.INDEXED),
    0xA9: ('ADC', 2, 'ACCA', AddressMode.INDEXED),
    0xAA: ('ORA', 2, 'ACCA', AddressMode.INDEXED),
    0xAB: ('ADD', 2, 'ACCA', AddressMode.INDEXED),
    0xAC: ('CPX', 2, None, AddressMode.INDEXED),
    0xAD: ('JSR', 2, None, AddressMode.INDEXED),
    0xAE: ('LOS', 2, None, AddressMode.INDEXED),
    0xAF: ('STS', 2, None, AddressMode.INDEXED),
    0xB0: ('SUB', 3, 'ACCA', AddressMode.EXTENDED),
    0xB1: ('CMP', 3, 'ACCA', AddressMode.EXTENDED),
    0xB2: ('SBC', 3, 'ACCA', AddressMode.EXTENDED),
    0xB4: ('AND', 3, 'ACCA', AddressMode.EXTENDED),
    0xB5: ('BIT', 3, 'ACCA', AddressMode.EXTENDED),
    0xB6: ('LDA', 3, 'ACCA', AddressMode.EXTENDED),
    0xB7: ('STA', 3, 'ACCA', AddressMode.EXTENDED),
    0xB8: ('EOR', 3, 'ACCA', AddressMode.EXTENDED),
    0xB9: ('ADC', 3, 'ACCA', AddressMode.EXTENDED),
    0xBA: ('ORA', 3, 'ACCA', AddressMode.EXTENDED),
    0xBB: ('ADD', 3, 'ACCA', AddressMode.EXTENDED),
    0xBC: ('CPX', 3, None, AddressMode.EXTENDED),
    0xBD: ('JSR', 3, None, AddressMode.EXTENDED),
    0xBE: ('LOS', 3, None, AddressMode.EXTENDED),
    0xBF: ('STS', 3, None, AddressMode.EXTENDED),
    0xC0: ('SUB', 2, 'ACCB', AddressMode.IMMEDIATE),
    0xC1: ('CMP', 2, 'ACCB', AddressMode.IMMEDIATE),
    0xC2: ('SBC', 2, 'ACCB', AddressMode.IMMEDIATE),
    0xC4: ('AND', 2, 'ACCB', AddressMode.IMMEDIATE),
    0xC5: ('BIT', 2, 'ACCB', AddressMode.IMMEDIATE),
    0xC6: ('LDA', 2, 'ACCB', AddressMode.IMMEDIATE),
    0xC8: ('EOR', 2, 'ACCB', AddressMode.IMMEDIATE),
    0xC9: ('ADC', 2, 'ACCB', AddressMode.IMMEDIATE),
    0xCA: ('ORA', 2, 'ACCB', AddressMode.IMMEDIATE),
    0xCB: ('ADD', 2, 'ACCB', AddressMode.IMMEDIATE),
    0xCE: ('LDX', 3, None, AddressMode.IMMEDIATE),
    0xD0: ('SUB', 2, 'ACCB', AddressMode.DIRECT),
    0xD1: ('CMP', 2, 'ACCB', AddressMode.DIRECT),
    0xD2: ('SBC', 2, 'ACCB', AddressMode.DIRECT),
    0xD4: ('AND', 2, 'ACCB', AddressMode.DIRECT),
    0xD5: ('BIT', 2, 'ACCB', AddressMode.DIRECT),
    0xD6: ('LDA', 2, 'ACCB', AddressMode.DIRECT),
    0xD7: ('STA', 2, 'ACCB', AddressMode.DIRECT),
    0xD8: ('EOR', 2, 'ACCB', AddressMode.DIRECT),
    0xD9: ('ADC', 2, 'ACCB', AddressMode.DIRECT),
    0xDA: ('ORA', 2, 'ACCB', AddressMode.DIRECT),
    0xDB: ('ADD', 2, 'ACCB', AddressMode.DIRECT),
    0xDE: ('LDX', 2, None, AddressMode.DIRECT),
    0xDF: ('STX', 2, None, AddressMode.DIRECT),
    0xE0: ('SUB', 2, 'ACCB', AddressMode.INDEXED),
    0xE1: ('CMP', 2, 'ACCB', AddressMode.INDEXED),
    0xE2: ('SBC', 2, 'ACCB', AddressMode.INDEXED),
    0xE4: ('AND', 2, 'ACCB', AddressMode.INDEXED),
    0xE5: ('BIT', 2, 'ACCB', AddressMode.INDEXED),
    0xE6: ('LDA', 2, 'ACCB', AddressMode.INDEXED),
    0xE7: ('STA', 2, 'ACCB', AddressMode.INDEXED),
    0xE8: ('EOR', 2, 'ACCB', AddressMode.INDEXED),
    0xE9: ('ADC', 2, 'ACCB', AddressMode.INDEXED),
    0xEA: ('ORA', 2, 'ACCB', AddressMode.INDEXED),
    0xEB: ('ADD', 2, 'ACCB', AddressMode.INDEXED),
    0xEE: ('LDX', 2, None, AddressMode.INDEXED),
    0xEF: ('STX', 2, None, AddressMode.INDEXED),
    0xF0: ('SUB', 3, 'ACCB', AddressMode.EXTENDED),
    0xF1: ('CMP', 3, 'ACCB', AddressMode.EXTENDED),
    0xF2: ('SBC', 3, 'ACCB', AddressMode.EXTENDED),
    0xF4: ('AND', 3, 'ACCB', AddressMode.EXTENDED),
    0xF5: ('BIT', 3, 'ACCB', AddressMode.EXTENDED),
    0xF6: ('LDA', 3, 'ACCB', AddressMode.EXTENDED),
    0xF7: ('STA', 3, 'ACCB', AddressMode.EXTENDED),
    0xF8: ('ADC', 3, 'ACCB', AddressMode.EXTENDED),
    0xF9: ('ADC', 3, 'ACCB', AddressMode.EXTENDED),
    0xFA: ('ORA', 3, 'ACCB', AddressMode.EXTENDED),
    0xFB: ('ADD', 3, 'ACCB', AddressMode.EXTENDED),
    0xFE: ('LDX', 3, None, AddressMode.EXTENDED),
    0xFF: ('STX', 3, None, AddressMode.EXTENDED)
}
